### ISSUE TITLE
usage of this package for Inner eml data in ParseEmailFilesV2 vs. ParseEmailFiles and saving as incident file attachment

### ISSUE THREAD

**Issue by cah-zachary-rouse** [demisto/parse-emails#62]
I'm not sure where to open this issue, apologies in advance.

We currently use `ParseEmailFiles` which uses older code implementation and we know it is deprecated.  However, `ParseEmailFilesV2` which uses this `parse-emails` python package no longer saves the Inner eml file as a file attachment to the incident which we need to have in our playbook.  We are not able to utilize `ParseEmailFilesV2` because of this change using this python package.  The previous implementation of code inside `ParseEmailFiles` saves all nested attachments as files to the incident.

for reference:
https://github.com/demisto/content/blob/7d85de4e9199699106debb2d0ee3b84f82c8efbd/Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py#LL3345C32-L3345C32

`ParseEmailFilesV2` is working great with this package to identify the correct Inner eml and uses that data in context, however we no longer get the `Inner` eml file `saved to the incident as a file attachment`.  

Would it be appropriate for this package to have the `EmailParser` class be able to return the `Inner` eml file content so that `ParseEmailFilesV2` can add support for saving the `Inner` eml file as an incident file attachment.

https://github.com/demisto/parse-emails/blob/c2a23ba17047136116419c2bba1bb002a3df8675/parse_emails/handle_eml.py#L243

`ParseEmailFilesV2` already has a function to save files as an attachment to the incident, we just need `EmailParser` to be able to return the file content when `Inner` eml is being used.

https://github.com/demisto/content/blob/7d85de4e9199699106debb2d0ee3b84f82c8efbd/Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py#L48

I hope I explained this issue well enough.  Thanks!

**Comment by moishce** [comment]
Hi @cah-zachary-rouse 
Thanks for the update and sorry for the late reply.
According to my test, the ParseEmailFilesV2 already returns the internal email as an attachment to the war room
<img width="1427" alt="Screenshot 2023-12-06 at 12 03 50" src="https://github.com/demisto/parse-emails/assets/112559840/5de17d1b-fbab-4b9d-a394-ddf877e1f9c3">
If you still see different behavior, please attach an email file that this is happening.
